# Generated by Django 5.0.7 on 2024-11-06 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analyzer', '0003_alter_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255, unique=True)),
                ('search_count', models.IntegerField(default=0)),
                ('average_rating', models.FloatField(blank=True, null=True)),
                ('last_searched', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
